language: python
python:
  - '2.7'
install: pip install pip --upgrade
script: make test
deploy:
  provider: pypi
  user: pyunicore
  password:
    secure: paJGvQXIb7YnXs2QoytbNHwAX7pBTy79jDt0hcABRul3QiGi57u39tdOVlTSG+T4urj48gA9TeGXrwmTJVWZm3BVLAskXNXL1Bv3Zap9GY2Kzm7LXEnisk33mP6BMYw9sLBKqb6b5NZxwkzoYP+mbSimHeQ3YmOJ0IvcrEMbkFfea0j53yWW8EJO36HGeQaADPVzo/lMy4JKUn37AHxCTdYbL8GdczUIboUjxElgaKM563XJ/Ev8Ja33HAUwG3C7jj0IXWgLl1jiU3Pc1YuZ95b5o+AQR7sRHwfCuAN84jph9MaA+Hn/5KnM1qMmswS82HGmYYfaIxZXJv0eBe5H06cMZb1AlXffhvPr4LJEnSOpZA0gDeOf8RYGqeYV/1DUAlbNODvk9350r9oRCdCbR89y4/yxgX56gUjDhp6qrKWtHgQJQ7Ub8nFIiJq3/uicphFDOX3ve3gXDPPetTKK8dVaU+U2hg2V/WX5unbMXxMo7MHLDIgAJuwZmWp9cZwi32fYz94JvvKz10073QfYpN5Td+LTQmKH3fiF2ilT2EOG+W3u7eudCH2aqPeG4wQVcnNZjmZi2Tfyj+bkMlsTSOec6ncO+1eOMs5nG9+9bdO71GgYadbvuxxEZK8SnCkxlzhBn/xFO7oRILtg+0ARvdt009pgcu0viLcQ7WKm61g=
